import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:perfume_app/features/products/data/models/product_model.dart';

final mockCatalog = [
  ProductModel(
    id: 'p1',
    name: 'Campus Citrus Drive',
    nameLower: 'campus citrus drive',
    searchPrefixes: ['ca', 'cam', 'camp', 'campu', 'campus'],
    brand: 'Campus',
    price: 1000.0,
    gender: 'men',
    season: 'summer',
    fragranceFamily: 'Citrus',
    notes: ['citrus', 'lemon', 'orange'],
    imageUrls: ['https://example.com/p1.png'],
    description: 'Fresh summer scent',
    categoryName: 'Perfumes',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    occasion: 'daily',
    time: 'day',
    intensity: 'medium',
    topNotes: ['lemon'],
    middleNotes: ['orange'],
    baseNotes: ['musk'],
    tags: ['fresh', 'clean', 'sporty'],
    stock: 10,
  ),
  ProductModel(
    id: 'p2',
    name: 'Cedar Class 01',
    nameLower: 'cedar class 01',
    searchPrefixes: ['ce', 'ced', 'ceda', 'cedar'],
    brand: 'Cedar',
    price: 1500.0,
    gender: 'men',
    season: 'winter',
    fragranceFamily: 'Woody',
    notes: ['cedar', 'woody', 'amber'],
    imageUrls: ['https://example.com/p2.png'],
    description: 'Elegant woody scent',
    categoryName: 'Perfumes',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    occasion: 'formal',
    time: 'night',
    intensity: 'strong',
    topNotes: ['cedar'],
    middleNotes: ['amber'],
    baseNotes: ['woody'],
    tags: ['classic', 'elegant', 'warm'],
    stock: 5,
  ),
  ProductModel(
    id: 'p3',
    name: 'Vanilla Sky',
    nameLower: 'vanilla sky',
    searchPrefixes: ['va', 'van', 'vani', 'vanil', 'vanilla'],
    brand: 'Gourmand',
    price: 800.0,
    gender: 'women',
    season: 'autumn',
    fragranceFamily: 'Oriental',
    notes: ['vanilla', 'sweet', 'caramel'],
    imageUrls: ['https://example.com/p3.png'],
    description: 'Sweet vanilla scent',
    categoryName: 'Perfumes',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    occasion: 'date',
    time: 'night',
    intensity: 'strong',
    topNotes: ['sweet'],
    middleNotes: ['caramel'],
    baseNotes: ['vanilla'],
    tags: ['sweet', 'romantic'],
    stock: 15,
  ),
];
