// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBobsOtF0Yw3KdCDNny5iVVu0aMNpaVpLU',
    appId: '1:480328445067:web:8333a351918d53e8ab788e',
    messagingSenderId: '480328445067',
    projectId: 'perfume-app-9999',
    authDomain: 'perfume-app-9999.firebaseapp.com',
    storageBucket: 'perfume-app-9999.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABrp7kD7jUX4ZHWRmjyfg02qgRKFKH0m4',
    appId: '1:480328445067:android:468cfed2ec771e87ab788e',
    messagingSenderId: '480328445067',
    projectId: 'perfume-app-9999',
    storageBucket: 'perfume-app-9999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKcxmVIU1V60RbGSL-WQ2ZQoPRG_m9rKY',
    appId: '1:480328445067:ios:ea4abf8d22e91571ab788e',
    messagingSenderId: '480328445067',
    projectId: 'perfume-app-9999',
    storageBucket: 'perfume-app-9999.firebasestorage.app',
    iosBundleId: 'com.example.perfumeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKcxmVIU1V60RbGSL-WQ2ZQoPRG_m9rKY',
    appId: '1:480328445067:ios:ea4abf8d22e91571ab788e',
    messagingSenderId: '480328445067',
    projectId: 'perfume-app-9999',
    storageBucket: 'perfume-app-9999.firebasestorage.app',
    iosBundleId: 'com.example.perfumeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBobsOtF0Yw3KdCDNny5iVVu0aMNpaVpLU',
    appId: '1:480328445067:web:05725308826d9170ab788e',
    messagingSenderId: '480328445067',
    projectId: 'perfume-app-9999',
    authDomain: 'perfume-app-9999.firebaseapp.com',
    storageBucket: 'perfume-app-9999.firebasestorage.app',
  );

}