const Set<String> budgetContextKeywords = {
  'budget',
  'under',
  'around',
  'max',
  'maximum',
  'at most',
  'price',
  'egp',
  'pound',
  'جنيه',
  'ميزانية',
  'ميزانيتي',
  'تحت',
  'اخرها',
  'آخرها',
  'بحد اقصى',
  'بالظبط',
  'بالضبط',
  'بسعر',
};

const Set<String> ageContextKeywords = {
  'age',
  'aged',
  'year old',
  'years old',
  'عمره',
  'عمرها',
  'سنه',
  'سنة',
};

const Set<String> cheapKeywords = {
  'cheap',
  'cheaper',
  'cheapest',
  'more affordable',
  'most affordable',
  'less expensive',
  'lowest price',
  'best price',
  'minimum price',
  'lower budget',
  'budget',
  'economy',
  'economic',
  'لا خليه أرخص',
  'خليه أرخص',
  'رخيص',
  'ارخص',
  'اقل',
  'اوفر',
  'اخفض',
  'سعر اقل',
  'اقل شوية',
  'اقل شويه',
  'ارخص شوية',
  'ارخص شويه',
  'اقتصادي',
  'بسعر قليل',
  'هاتلي أرخص شوية',
};

const Set<String> premiumKeywords = {
  'vip',
  'masterpiece',
  'money is no object',
  'money is no issue',
  'ignore budget',
  'مهما كان السعر',
  'الفلوس مش مشكله',
  'الفلوس مش مشكلة',
  'تحفه فنيه',
  'تحفة فنية',
  'تحفه',
  'تحفة',
};

const Set<String> compromiseKeywords = {
  'حل وسط',
  'يرضينا',
  'balanced',
  'compromise',
  'middle ground',
  'versatile',
  'مش قوي اوي',
  'مش حلو اوي',
  'مش مسكر قوي',
};

const List<String> summaryTailMarkers = [
  'في النهايه',
  'في النهاية',
  'بالنهايه',
  'بالنهاية',
  'الخلاصه',
  'الخلاصة',
  'المهم',
  'in the end',
  'bottom line',
  'what i need',
  'i need',
];

const Set<String> greetingPhrases = {
  'اهلا',
  'اهلا بيك',
  'مرحبا',
  'السلام عليكم',
  'السلام عليكم ورحمة الله',
  'السلام عليكم ورحمة الله وبركاته',
  'وعليكم السلام',
  'وعليكم السلام ورحمة الله',
  'وعليكم السلام ورحمة الله وبركاته',
  'hello',
  'hi',
  'hey',
};

const Set<String> greetingTokens = {
  'اهلا',
  'مرحبا',
  'السلام',
  'عليكم',
  'بيك',
  'بك',
  'وعليكم',
  'ورحمة',
  'رحمة',
  'الله',
  'وبركاته',
  'بركاته',
  'hello',
  'hi',
  'hey',
  'welcome',
};

const Set<String> perfumeTopicKeywords = {
  'عطر',
  'برفان',
  'بارفان',
  'perfume',
  'fragrance',
  'scent',
  'smell',
  'ريحة',
  'ريحه',
  'note',
  'notes',
  'نوتات',
};

const Set<String> continueWithCurrentStateKeywords = {
  'اي حاجه',
  'أي حاجة',
  'اي حاجة',
  'أي حاجه',
  'اي شي',
  'أي شي',
  'anything',
  'any thing',
  'whatever',
  'anything works',
  'any option',
  'open budget',
  'budget open',
  'no budget limit',
  'no limit',
  'unlimited',
  'مفتوح',
  'مفتوحه',
  'مفتوحة',
  'الميزانيه مفتوحه',
  'الميزانية مفتوحة',
};

const Set<String> summaryKeywords = {
  'لخصلي',
  'لخص لي',
  'لخص',
  'الملخص',
  'الخلاصة',
  'انا طالب ايه',
  'أنا طالب ايه',
  'انا طلبت ايه',
  'أنا طلبت ايه',
  'what am i asking for',
  'summarize',
  'summary',
  'recap',
  'sum up',
};

const Set<String> contextResetKeywords = {
  'سيبك من كل ده',
  'سيبك من ده',
  'انسى اللي فات',
  'غير الموضوع',
  'موضوع تاني',
  'خلينا نبدأ من جديد',
  'ابدأ من جديد',
  'ابدء من جديد',
  'restart',
  'start over',
  'ignore that',
  'ignore all that',
  'forget that',
  'instead i want',
  'actually i want',
};

const Set<String> lighterModifiers = {
  'اهدى',
  'أهدى',
  'اهدي',
  'أهدي',
  'اخف',
  'أخف',
  'lighter',
  'less strong',
  'softer',
};

const Set<String> strongerModifiers = {
  'اقوى',
  'أقوى',
  'اقوي',
  'أقوي',
  'اقوى شويه',
  'اقوى شوية',
  'خليه أقوى',
  'stronger',
  'more projection',
  'heavier',
};

const Set<String> sweeterModifiers = {
  'حلو اكتر',
  'اكتر حلاوه',
  'اكتر حلاوة',
  'sweeter',
  'more sweet',
};

const Set<String> revertModifiers = {
  'رجع زي الاول',
  'رجعني زي الاول',
  'رجعها زي الاول',
  'خليها زي الاول',
  'ارجع زي الاول',
  'رجع القوه زي الاول',
  'رجع القوة زي الاول',
  'زي الاول',
  'زي ما كان',
  'ارجع',
  'رجع زي الأول',
  'undo',
  'revert',
  'go back',
};

const Set<String> compareKeywords = {
  'قارن',
  'الفرق',
  'فرق',
  'مقارنة',
  'بينهم',
  'بين',
  'أيهم',
  'ايهم',
  'افضل',
  'أفضل',
  'compare',
  'difference',
  'better',
  'versus',
  'vs',
};

const Set<String> followUpKeywords = {
  'tell me more',
  'tell me about',
  'more about',
  'what about',
  'why this',
  'why that',
  'why did you recommend',
  'why did you suggest',
  'details about',
  'this one',
  'that one',
  'first',
  'second',
  'third',
  'اشمعنا',
  'ليه',
  'عشان ايه',
  'عشان اي',
  'قولي اكتر',
  'اكثر عن',
  'اكتر عن',
  'تفاصيل',
  'اعرفني',
  'اخبرني',
  'الاول',
  'الثاني',
  'الثالث',
  'عنه',
  'عنها',
  'عنهم',
  'شبهه',
  'زيه',
  'بديله',
  'بديل',
  'اقرب حاجه ليه',
  'أقرب حاجة ليه',
  'المتوفر شبهه ايه',
  'المتوفر شبهه ايه؟',
  'something similar',
  'something like it',
  'closest thing',
  'closest thing you have',
  'closest alternative',
  'if not',
  'alternative',
  'closest available',
};

const Set<String> availabilitySubstituteFollowUpKeywords = {
  'شبهه',
  'زيه',
  'بديله',
  'بديل',
  'اقرب حاجه ليه',
  'أقرب حاجة ليه',
  'المتوفر شبهه ايه',
  'المتوفر شبهه ايه؟',
  'something similar',
  'something like it',
  'closest thing',
  'closest thing you have',
  'closest alternative',
  'if not',
  'alternative',
  'closest available',
};

const Set<String> addTriggers = {
  'خليه',
  'خليها',
  'خلي',
  'خلها',
  'بس',
  'لكن',
  'with',
  'and',
  'make it',
  'make',
  'use',
  'ضيف',
  'حط',
  'add',
  'include',
  'وبال',
  'ب',
};

const Set<String> removeTriggers = {
  '\u0645\u0634 \u0628\u062d\u0628',
  'بدون',
  'بلاش',
  'من غير',
  'بدال',
  'بدل',
  'بلا',
  'مفيهاش',
  'مافيهوش',
  'مافيهاش',
  'ابعد',
  'ابتعد',
  'تجنب',
  'مش عايز',
  'without',
  'exclude',
  'excluding',
  'not',
  'no',
  'remove',
  'replace',
  'instead',
  'استبدل',
  'شيل',
  'احذف',
};

const Set<String> femaleRelationshipKeywords = {
  'خطيبتي',
  'مراتي',
  'مراته',
  'مراتك',
  'زوجتي',
  'والدتي',
  'والدته',
  'لوالدتي',
  'امي',
  'مامتي',
  'صاحبتي',
  'عروستي',
  'اختي',
  'بنتي',
  'حماتي',
  'wife',
  'fiancee',
  'mother',
  'mom',
  'sister',
  'daughter',
  'girlfriend',
};

const Set<String> maleRelationshipKeywords = {
  'ابني',
  'والدي',
  'زوجي',
  'جوزي',
  'خطيبي',
  'اخويا',
  'صاحبي',
  'بابا',
  'حمايا',
  'عريسي',
  'husband',
  'fiance',
  'father',
  'dad',
  'brother',
  'son',
  'boyfriend',
};
